### PR TITLE
Update Gradle wrapper to 3.4

### PR DESCRIPTION
**Pull request by friederbluemle**

### CODE REVIEW

**Comment by friederbluemle** [comment]
Commit amended for the (now) latest Gradle wrapper version 3.4

**Comment by friederbluemle** [comment]
@amuttsch Could you merge this please? :)

**Comment by amuttsch** [comment]
The sha256sum of gradle/wrapper/gradle-wrapper.jar doesn't match mine if I change the wrapper version to 3.4 and run `gradlew wrapper`. Any idea what might cause this difference?

**Comment by friederbluemle** [comment]
Hmm that is a very interesting observation.. I am not sure what causes the difference. I amended the commit again with the now latest version `3.4.1`. It was generated using the command

    ./gradlew wrapper --distribution-type=all --gradle-version=3.4.1

I did a test run with different versions locally, and I keep getting different values for `sha256sum gradle/wrapper/gradle-wrapper.jar`. My only guess is that Gradle must somehow dynamically generate the jar and it includes a timestamp or otherwise changing value.

**Comment by hatstand** [comment]
zip/jar files typically have timestamps for each file which makes building them non-deterministic.

**Comment by amuttsch** [comment]
Thanks for the clarification. I can also reproduce this behaviour by altering the version from 3.4 and 3.4.1 and getting a different sha256sum each time for a specific version.

I'll merge this once travis is done.

**Comment by friederbluemle** [comment]
Thanks :+1:

**Pull request merged**
