### PR TITLE
 Updated Library Grouping to have "Album Artist / Album"

### PR DESCRIPTION
**Pull request by physk**
Translations string XML files have been updated with the additional item under "pref_library_grouping_values" with my best guess at the translations. They have been commented, For someone who is multi-lingual to fix if needed :)

### CODE REVIEW

**Comment by amuttsch** [comment]
Looks good. Please remove all translations as they will be overridden by the next transifex translation pull. Also add the feature to the `CHANGELOG` file.

**Comment by physk** [comment]
@amuttsch There that should be done now :) Sorry i forgot to tick all the translation files when i committed (Hence the double commit)

**Comment by amuttsch** [comment]
Perfect, thanks for the PR :)

**Comment by remjg** [comment]
I was looking for the very interesting "album artist" grouping feature on Clementine Remote v12, until I realised I needed to set up my phone in English language to see the option. Seems like something went wrong, at least for the French translation.

**Pull request merged**
